import { mkdirSync } from "node:fs";
import path from "node:path";
import { PGlite } from "@electric-sql/pglite";
import { attachDatabasePool } from "@vercel/functions";
import { drizzle as drizzlePg } from "drizzle-orm/node-postgres";
import type { PgDatabase, PgQueryResultHKT } from "drizzle-orm/pg-core";
import { drizzle as drizzlePglite } from "drizzle-orm/pglite";
import { migrate as migratePglite } from "drizzle-orm/pglite/migrator";
import { Pool } from "pg";
import type { DatabaseConfig } from "@/lib/env";
import * as schema from "./schema";

export type Db = PgDatabase<PgQueryResultHKT, typeof schema>;
export type Tx = Parameters<Parameters<Db["transaction"]>[0]>[0];

/** Generated by `npm run db:generate`; applied by scripts/migrate.mjs on Postgres and here on PGlite. */
export const MIGRATIONS_FOLDER = path.join(process.cwd(), "drizzle");

/** Postgres for deployments; PGlite (in-process, migrated on open) for development and tests. */
export async function openDatabase(config: DatabaseConfig): Promise<Db> {
  if (config.kind === "postgres") {
    const pool = new Pool({ connectionString: config.url, max: 5 });
    // On Vercel Fluid compute this closes idle clients before the instance suspends. Elsewhere it does nothing.
    attachDatabasePool(pool);
    return drizzlePg({ client: pool, schema });
  }
  // PGlite creates its own directory but not missing parents (e.g. `.data/`).
  if (config.dataDir) mkdirSync(path.dirname(config.dataDir), { recursive: true });
  const client = config.dataDir ? new PGlite(config.dataDir) : new PGlite();
  const db = drizzlePglite({ client, schema });
  await migratePglite(db, { migrationsFolder: MIGRATIONS_FOLDER });
  return db;
}
